export const FALLBACK_RECIPES = [
  {
    idMeal: "fb001",
    strMeal: "Pork Cassoulet",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wxuvuv1511299147.jpg",
    strCategory: "Pork",
    strArea: "French",
    strInstructions: "A classic French dish with pork, beans, and herbs. Heat oil in a large pot, brown the pork, then add beans, herbs, and simmer for 2 hours.",
  },
  {
    idMeal: "fb002", 
    strMeal: "Chicken Teriyaki",
    strMealThumb: "https://www.themealdb.com/images/media/meals/64-1542208684.jpg",
    strCategory: "Chicken",
    strArea: "Japanese", 
    strInstructions: "Delicious chicken glazed with teriyaki sauce. Marinate chicken in soy sauce, grill, and glaze with teriyaki.",
  },
  {
    idMeal: "fb003",
    strMeal: "Beef Stroganoff", 
    strMealThumb: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    strCategory: "Beef",
    strArea: "Russian",
    strInstructions: "Tender beef in creamy mushroom sauce. Sauté beef strips, add mushrooms, cream, and serve over noodles.",
  },
  {
    idMeal: "fb004",
    strMeal: "Caesar Salad",
    strMealThumb: "https://www.themealdb.com/images/media/meals/x9uddp1583765678.jpg", 
    strCategory: "Vegetarian",
    strArea: "Italian",
    strInstructions: "Fresh romaine lettuce with caesar dressing. Toss lettuce with dressing, croutons, and parmesan cheese.",
  },
  {
    idMeal: "fb005",
    strMeal: "Fish and Chips",
    strMealThumb: "https://www.themealdb.com/images/media/meals/hvnqpw1495463016.jpg",
    strCategory: "Seafood", 
    strArea: "British",
    strInstructions: "Classic British fish and chips. Beer-batter white fish, deep fry, serve with thick-cut chips and mushy peas.",
  },
  {
    idMeal: "fb006",
    strMeal: "Pasta Carbonara",
    strMealThumb: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    strCategory: "Pasta",
    strArea: "Italian", 
    strInstructions: "Creamy pasta with bacon and eggs. Cook spaghetti, toss with egg mixture, crispy pancetta, and parmesan.",
  },
  {
    idMeal: "fb007",
    strMeal: "Chocolate Cake",
    strMealThumb: "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
    strCategory: "Dessert",
    strArea: "American",
    strInstructions: "Rich and moist chocolate cake. Mix dry ingredients, add wet ingredients, bake at 350°F for 30 minutes.",
  },
  {
    idMeal: "fb008", 
    strMeal: "Greek Salad",
    strMealThumb: "https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg",
    strCategory: "Vegetarian",
    strArea: "Greek",
    strInstructions: "Fresh vegetables with feta cheese. Combine tomatoes, cucumber, olives, onions, feta and olive oil.",
  },
  {
    idMeal: "fb009",
    strMeal: "Beef Tacos",
    strMealThumb: "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg", 
    strCategory: "Beef",
    strArea: "Mexican",
    strInstructions: "Authentic Mexican tacos with fresh toppings. Season ground beef, warm tortillas, add lettuce, tomato, cheese.",
  }
];

export const FALLBACK_CATEGORIES = [
  { idCategory: "1", strCategory: "Beef", strCategoryThumb: "https://www.themealdb.com/images/category/beef.png", strCategoryDescription: "Beef dishes" },
  { idCategory: "2", strCategory: "Chicken", strCategoryThumb: "https://www.themealdb.com/images/category/chicken.png", strCategoryDescription: "Chicken dishes" },
  { idCategory: "3", strCategory: "Dessert", strCategoryThumb: "https://www.themealdb.com/images/category/dessert.png", strCategoryDescription: "Sweet desserts" },
  { idCategory: "4", strCategory: "Pasta", strCategoryThumb: "https://www.themealdb.com/images/category/pasta.png", strCategoryDescription: "Pasta dishes" },
  { idCategory: "5", strCategory: "Seafood", strCategoryThumb: "https://www.themealdb.com/images/category/seafood.png", strCategoryDescription: "Fresh seafood" },
  { idCategory: "6", strCategory: "Vegetarian", strCategoryThumb: "https://www.themealdb.com/images/category/vegetarian.png", strCategoryDescription: "Vegetarian meals" },
  { idCategory: "7", strCategory: "Pork", strCategoryThumb: "https://www.themealdb.com/images/category/pork.png", strCategoryDescription: "Pork dishes" },
  { idCategory: "8", strCategory: "Lamb", strCategoryThumb: "https://www.themealdb.com/images/category/lamb.png", strCategoryDescription: "Lamb dishes" },
];